### ISSUE TITLE
"could not get auth_key from airVPN's login page"

### ISSUE THREAD

**Issue by omzig10** [BiglySoftware/BiglyBT-plugin-vpn_helper#1]
This seems like something new, but it looks like the plugin no longer is able to log into the AirVPN site and pull the port in.

**Comment by ddwr450** [comment]
New BiglyBT install; same issue.

**Comment by TuxPaper** [comment]
Looks like AirVPN put a blocker preventing non-web browsers from loading their login page.  Will look into it, but if this is their attitude, I'm not sure how much can be done.

**Comment by TuxPaper** [comment]
The workaround for now is to 

1) disable the "Use VPN's Port Forwarding", 
2) login to AirVPN website and check if you have a Open Port created (Client Area->Forwarded Ports).  
2.1) If not, create one (Click the add button, don't need to enter anything fields). 
3) Set your ports numbers in BiglyBT under Options->Connection to that port.

Only need to do this once.  I'm pretty sure once you have a port number setup on the AirVPN website, it's permanent.

**Comment by ddwr450** [comment]
Thank you for looking into this!  The workaround functions perfectly.

**Comment by TuxPaper** [comment]
Latest plugin version now has the VPN Port forwarding options removed, with instructions on how to manually create an open port.  We won't be able to get the open port number automatically until/unless AirVPN decides to support an API/CLI/RPC for it.
