### ISSUE TITLE
Unable to download plugin.

### ISSUE THREAD

**Issue by kevinlekiller** [BiglySoftware/BiglyBT-plugin-vpn_helper#3]
When trying to download the plugin from https://plugins.biglybt.com/ an error occurs:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>A125BFA73CF4265B</RequestId>
<HostId>
7eJZcO2H9LIrL16w5jvP71uapL2O20RLRdN+/UilKJPwQoO4zKFv2+QNES6HchL0JlLPen0V23I=
</HostId>
</Error>
```

Edit: Can install the plugin by putting `biglybt://install-plugin/vpn_helper` in File->Open->URL in biglybt.

**Comment by TuxPaper** [comment]
The website was linking to an older version of the plugin which has been removed.  I've fixed it now.

This was a bigger issue that more than just this plugin, so thanks very much for the report.
